# Generated by Django 5.1.6 on 2026-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.CharField(db_index=True, max_length=64)),
                ("chunk_index", models.PositiveIntegerField()),
                ("chunk_text", models.TextField()),
                ("source", models.CharField(max_length=200)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("embedding", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document_id"], name="knowledge_d_documen_d1c56c_idx"
                    )
                ],
            },
        ),
    ]
